### ISSUE TITLE
README.md needed

### ISSUE THREAD

**Issue by dcecile** [mongodb/docs-primer#2]
I figured out that I need to use Python2 and I need to run `giza make html`, but I end up with a whole slew of errors (see [attached](https://github.com/mongodb/docs-primer/files/425986/errors.txt) for full list):

```
source/tutorial/install-mongodb-on-debian.txt:65: SEVERE: Problems with "include" directive path: source/includes/fact-uninstall.rst
source/tutorial/install-mongodb-on-debian.txt:67: SEVERE: Problems with "include" directive path: source/includes/steps/uninstall-mongodb-on-debian.rst
source/includes/example-java-single-field-index-post.rst:42: ERROR: Unexpected indentation.
source/includes/example-java-update-embedded-field-post.rst:57: ERROR: Unexpected indentation.
```

If the only problem is that I'm missing some steps, then a README.md would help :wink:

**Comment by kay-kim** [comment]
Hi -- 
thanks for the message. 

I believe `giza --level info -f --serial make html`  should fix the issues.

Regards,
Kay Kim
